apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: django-app-route
  namespace: {{ .Values.gateway.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: app
          port: 80
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: X-Request-ID
                value: "%REQ(RandomUID)%"
            set:
              - name: X-Forwarded-Proto
                value: "http"
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            set:
              - name: Strict-Transport-Security
                value: "max-age=16000000"
      timeouts:
        backendRequest: 300s
