apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: static-files-route
  namespace: {{ .Values.gateway.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /static
      backendRefs:
        - name: nginx
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /media
      backendRefs:
        - name: nginx
          port: 80
