{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-app-ingress
  namespace: {{ .Values.ingress.namespace }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_input_headers "X-Request-ID: $request_id";
      more_set_headers "X-Forwarded-Proto: $scheme";
      more_set_headers "Strict-Transport-Security: max-age=16000000";
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.django.host }}
      http:
        paths:
          - path: {{ .Values.django.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.django.serviceName }}
                port:
                  number: {{ .Values.django.servicePort }}
  {{- if .Values.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.django.host }}
      secretName: {{ .Values.tls.secretName }}
  {{- end }}
{{- end }}
