name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC every day

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v44.0.4
        env:
          LOG_LEVEL: debug
          RENOVATE_REPOSITORIES: victory-sokolov/django-rest
        with:
          configurationFile: renovate.json
          token: ${{ github.token }}
